services:
  arcurepharma:
    image: node:24-alpine
    container_name: arcurepharma-dev
    working_dir: /warsi

    volumes:
      - ./:/warsi

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=development

    # Keep the container alive for manual commands
    command: tail -f /dev/null
