/*
mport img0 from "../assets/pics/products/0.jpg";
imagePath:"img0",
imageUrl: "https://img.jpg"
*/

export const products = [
  {
    id: 1,
    name: "NeuroPlus Essential",
    price: 45.99,
    category: "Brain Health",
    shortDescription: "Advanced cognitive support for mental clarity and focus.",
    description: "NeuroPlus Essential is formulated with scientifically backed ingredients to enhance cognitive function, improve memory retention, and support long-term brain health. Ideal for professionals and students seeking a mental edge.",
    imagePath:"",
    imageUrl: "",
    features: ["Boosts Focus", "Supports Memory", "Natural Ingredients"]
  },
  {
    id: 2,
    name: "VitaGlow Complex",
    price: 29.50,
    category: "Supplements",
    shortDescription: "Daily multivitamin for radiant skin and immune support.",
    description: "Our VitaGlow Complex provides 100% of your daily required vitamins plus a proprietary blend of antioxidants. It supports cellular regeneration, giving your skin a natural, healthy glow while strengthening your immune system.",
    imagePath: "",
    imageUrl: "",
    features: ["Antioxidant Rich", "Immune Defense", "Gluten-Free"]
  },
  {
    id: 3,
    name: "DeepSleep Melatonin",
    price: 18.99,
    category: "Wellness",
    shortDescription: "Natural sleep aid for a restful night and refreshed morning.",
    description: "Designed for those struggling with occasional sleeplessness. Our non-habit-forming formula helps you fall asleep faster and stay asleep longer, ensuring you wake up feeling revitalized without morning grogginess.",
    imagePath: "",
    imageUrl: "",
    features: ["Fast Acting", "Non-Habit Forming", "Vegan"]
  },
  {
    id: 4,
    name: "PureFlex Joint Support",
    price: 34.00,
    category: "Joint Care",
    shortDescription: "Enhanced mobility and joint health for active lifestyles.",
    description: "PureFlex combines Glucosamine, Chondroitin, and Turmeric to provide a powerful anti-inflammatory effect. Specifically engineered for athletes and those looking to maintain joint flexibility and reduce discomfort.",
    imagePath: "",
    imageUrl: "",
    features: ["Reduces Inflammation", "Supports Cartilage", "High Potency"]
  },
  {
    id: 5,
    name: "HydraPure Electrolytes",
    price: 22.00,
    category: "Performance",
    shortDescription: "Maximum hydration for peak physical performance.",
    description: "Stay hydrated and maintain electrolyte balance with HydraPure. Our sugar-free formula provides essential minerals to prevent cramping and sustain energy levels during intense physical activity.",
    imagePath: "",
    imageUrl: "",
    features: ["Zero Sugar", "Rapid Hydration", "Natural Flavors"]
  },
  {
    id: 6,
    name: "OptiVision Guard",
    price: 38.50,
    category: "Eye Health",
    shortDescription: "Protect your vision against blue light and eye strain.",
    description: "With Lutein and Zeaxanthin, OptiVision Guard helps protect your eyes from the harmful effects of digital screens. Perfect for those who spend significant time on computers and mobile devices.",
    imagePath: "",
    imageUrl: "",
    features: ["Blue Light Shield", "Macular Support", "Clinically Proven"]
  },
  {
    id: 7,
    name: "ImmunoShield Pro",
    price: 32.99,
    category: "Immune Support",
    shortDescription: "High-potency Vitamin C and Zinc for immune defense.",
    description: "ImmunoShield Pro is designed to fortify your body's natural defenses with a blend of Vitamin C, Zinc, and Elderberry extract.",
    imagePath: "",
    imageUrl: "",
    features: ["High Vitamin C", "Zinc Boosted", "Daily Support"]
  }
  /*,
  {
    id: 8,
    name: "CardioVive Plus",
    price: 42.00,
    category: "Heart Health",
    shortDescription: "Support cardiovascular health and circulation.",
    description: "CardioVive Plus contains Omega-3 fatty acids and CoQ10 to support a healthy heart and maintain optimal blood pressure levels.",
    imagePath: "",
    imageUrl: "",
    features: ["Omega-3 Rich", "Heart Strength", "Natural Extract"]
  },
  {
    id: 9,
    name: "ZenMind Chill",
    price: 26.50,
    category: "Mental Wellness",
    shortDescription: "Ease stress and promote relaxation naturally.",
    description: "ZenMind uses Ashwagandha and L-Theanine to help your body manage stress and maintain a calm, focused mindset throughout the day.",
    imagePath: "",
    imageUrl: "",
    features: ["Stress Relief", "Adaptogenic", "Calming"]
  },
  {
    id: 10,
    name: "MetaboRise Energy",
    price: 39.99,
    category: "Metabolism",
    shortDescription: "Boost metabolic rate and natural energy levels.",
    description: "MetaboRise uses green tea extract and B-vitamins to support a healthy metabolism and provide sustained energy without the crash.",
    imagePath: "",
    imageUrl: "",
    features: ["Energy Boost", "Metabolic Support", "Clean Ingredients"]
  },
  {
    id: 11,
    name: "DigestEase Enzyme",
    price: 24.95,
    category: "Digestive Health",
    shortDescription: "Advanced enzyme blend for comfortable digestion.",
    description: "DigestEase helps break down fats, proteins, and carbohydrates, reducing bloating and improving nutrient absorption after meals.",
    imagePath: "",
    imageUrl: "",
    features: ["Enzyme Blend", "Reduces Bloat", "Gut Health"]
  },
  {
    id: 12,
    name: "PureBiotix 50B",
    price: 48.00,
    category: "Digestive Health",
    shortDescription: "High-dose probiotic for balanced gut flora.",
    description: "Featuring 50 billion CFU and 12 distinct strains, PureBiotix supports a healthy gut microbiome and regular digestive function.",
    imagePath: "",
    imageUrl: "",
    features: ["50B CFU", "Multi-Strain", "Shelf Stable"]
  },
  {
    id: 13,
    name: "BioHair Vitality",
    price: 35.00,
    category: "Beauty",
    shortDescription: "Nutrients for stronger hair and glowing skin.",
    description: "BioHair combines Biotin with Collagen and Keratin to stimulate hair growth and improve skin elasticity from the inside out.",
    imagePath: "",
    imageUrl: "",
    features: ["Biotin Boost", "Collagen Support", "Nail Health"]
  },
  {
    id: 14,
    name: "OsteoShield Calcium+",
    price: 27.50,
    category: "Bone Health",
    shortDescription: "Essential minerals for strong, healthy bones.",
    description: "OsteoShield provides a balanced ratio of Calcium, Magnesium, and Vitamin D3 to support bone density and prevent mineral deficiency.",
    imagePath: "",
    imageUrl: "",
    features: ["Bone Density", "Vitamin D3", "Mineral Rich"]
  },
  {
    id: 15,
    name: "IronFlow Recovery",
    price: 19.99,
    category: "Vitality",
    shortDescription: "Gentle iron supplement for energy and vitality.",
    description: "IronFlow uses a highly absorbable form of iron that is gentle on the stomach, helping to fight fatigue and support red blood cell production.",
    imagePath: "",
    imageUrl: "",
    features: ["Gentle on Stomach", "High Absorption", "Energy Support"]
  },
  {
    id: 16,
    name: "ActiveAura Multi-Men",
    price: 31.00,
    category: "Supplements",
    shortDescription: "Tailored nutritional support for active men.",
    description: "A comprehensive multivitamin designed specifically for men's unique health needs, including prostate health and muscle recovery.",
    imagePath: "",
    imageUrl: "",
    features: ["Men's Health", "Daily Vitality", "Muscle Support"]
  },
  {
    id: 17,
    name: "ActiveAura Multi-Women",
    price: 31.00,
    category: "Supplements",
    shortDescription: "Complete multivitamin for women's daily wellness.",
    description: "Formulated to support hormone balance, bone health, and energy levels for women navigating busy, modern lifestyles.",
    imagePath: "",
    imageUrl: "",
    features: ["Hormone Support", "Bone Health", "Iron Free"]
  },
  {
    id: 18,
    name: "FocusFuel Focus",
    price: 49.00,
    category: "Brain Health",
    shortDescription: "Nootropic blend for long-lasting concentration.",
    description: "FocusFuel combines Caffeine with L-Theanine and Bacopa Monnieri for sharp focus without the jittery side effects of coffee.",
    imagePath: "",
    imageUrl: "",
    features: ["Sharp Focus", "Natural Nootropic", "No Crash"]
  },
  {
    id: 19,
    name: "ViraDefend Elderberry",
    price: 25.99,
    category: "Immune Support",
    shortDescription: "Concentrated elderberry extract for seasonal health.",
    description: "ViraDefend provides a potent dose of black elderberry antioxidants to help you stay healthy during challenging seasons.",
    imagePath: "",
    imageUrl: "",
    features: ["Elderberry Extract", "Antioxidant Power", "Kid Friendly"]
  },
  {
    id: 20,
    name: "OmegaPure Triple",
    price: 44.95,
    category: "Heart Health",
    shortDescription: "Maximum strength Omega-3 for heart and brain.",
    description: "Triple strength fish oil with high concentrations of EPA and DHA to support heart health, brain function, and joint comfort.",
    imagePath: "",
    imageUrl: "",
    features: ["High EPA/DHA", "Triple Strength", "No Fishy Burps"]
  },
  {
    id: 21,
    name: "PureMag Calm",
    price: 23.00,
    category: "Wellness",
    shortDescription: "Magnesium glycinate for muscle and sleep support.",
    description: "PureMag is a highly bioavailable magnesium supplement that helps relax muscles and supports a calm nervous system for better sleep.",
    imagePath: "",
    imageUrl: "",
    features: ["Muscle Relax", "Better Sleep", "Highly Absorbable"]
  },
  {
    id: 22,
    name: "LiverRevive Detox",
    price: 36.50,
    category: "Vitality",
    shortDescription: "Support your body's natural detoxification process.",
    description: "Combining Milk Thistle, Dandelion, and Artichoke, LiverRevive supports liver function and healthy digestion.",
    imagePath: "",
    imageUrl: "",
    features: ["Milk Thistle", "Liver Support", "Natural Cleanse"]
  },
  {
    id: 23,
    name: "TestoPeak Performance",
    price: 55.00,
    category: "Performance",
    shortDescription: "Natural testosterone support for men's health.",
    description: "Using Fenugreek and Tribulus Terrestris, TestoPeak supports muscle growth, energy levels, and libido in a completely natural way.",
    imagePath: "",
    imageUrl: "",
    features: ["Muscle Growth", "Natural Drive", "Energy Support"]
  },
  {
    id: 24,
    name: "FemBalance Support",
    price: 33.00,
    category: "Wellness",
    shortDescription: "Natural harmony for women's endocrine system.",
    description: "FemBalance uses Chasteberry and Magnesium to help manage cycle-related discomfort and maintain emotional balance.",
    imagePath: "",
    imageUrl: "",
    features: ["Hormone Balance", "PMS Relief", "Natural Herbs"]
  },
  {
    id: 25,
    name: "ClearSkin Probiotic",
    price: 37.99,
    category: "Beauty",
    shortDescription: "Target the gut-skin axis for clearer skin.",
    description: "A specialized probiotic strain blend designed to reduce systemic inflammation and support a clear, healthy complexion from within.",
    imagePath: "",
    imageUrl: "",
    features: ["Clear Complexion", "Anti-Inflammatory", "Dermatologist Tested"]
  },
  {
    id: 26,
    name: "GlucoGuard Balance",
    price: 41.00,
    category: "Vitality",
    shortDescription: "Support healthy blood sugar levels naturally.",
    description: "Using Chromium and Cinnamon Bark, GlucoGuard helps your body manage insulin response and maintain stable energy throughout the day.",
    imagePath: "",
    imageUrl: "",
    features: ["Blood Sugar", "Insulin Support", "Metabolic Health"]
  },
  {
    id: 27,
    name: "FlexCore Collagen",
    price: 39.50,
    category: "Joint Care",
    shortDescription: "Type II collagen for joint structural support.",
    description: "FlexCore provides specific collagen peptides that target joint cartilage, improving long-term mobility and structural integrity.",
    imagePath: "",
    imageUrl: "",
    features: ["Joint Structure", "Type II Collagen", "Active Lifestyle"]
  },
  {
    id: 28,
    name: "NitricOxide Surge",
    price: 28.00,
    category: "Performance",
    shortDescription: "Enhance blood flow and muscle pump during exercise.",
    description: "Formulated with L-Arginine and L-Citrulline to boost nitric oxide levels, improving oxygen delivery to hard-working muscles.",
    imagePath: "",
    imageUrl: "",
    features: ["Muscle Pump", "Blood Flow", "Workout Support"]
  },
  {
    id: 29,
    name: "SunD3 Liquid Drop",
    price: 15.99,
    category: "Immune Support",
    shortDescription: "High-absorption Vitamin D3 for bone and immune health.",
    description: "A convenient liquid formula that ensures maximum bioavailability for those needing a significant Vitamin D boost.",
    imagePath: "",
    imageUrl: "",
    features: ["Liquid Form", "High Absorption", "Immune Defense"]
  },
  {
    id: 30,
    name: "K2-Vitality Support",
    price: 22.50,
    category: "Heart Health",
    shortDescription: "Ensure calcium goes to your bones, not your arteries.",
    description: "Vitamin K2 (as MK-7) works synergistically with D3 to support cardiovascular health and optimal calcium utilization.",
    imagePath: "",
    imageUrl: "",
    features: ["Vitamin K2 MK-7", "Artery Health", "Synergistic"]
  },
  {
    id: 31,
    name: "AdrenalBoost Restore",
    price: 34.99,
    category: "Mental Wellness",
    shortDescription: "Recover from burnout and adrenal fatigue.",
    description: "A blend of B-vitamins and adaptogenic herbs like Rhodiola to help your body recover from chronic stress and restore vitality.",
    imagePath: "",
    imageUrl: "",
    features: ["Burnout Support", "Adrenal Health", "Energy Restore"]
  },
  {
    id: 32,
    name: "CoQ10 Heart Fuel",
    price: 49.99,
    category: "Heart Health",
    shortDescription: "Cellular energy for heart and vascular strength.",
    description: "High-dose CoQ10 to support mitochondrial function in the heart, providing the energy your cardiovascular system needs to thrive.",
    imagePath: "",
    imageUrl: "",
    features: ["CoQ10 Support", "Cell Energy", "Heart Strong"]
  },
  {
    id: 33,
    name: "PreBioFiber Fuel",
    price: 21.00,
    category: "Digestive Health",
    shortDescription: "Nourish your gut bacteria with premium fiber.",
    description: "A blend of soluble and insoluble fibers that act as food for your healthy probiotics, supporting regular bowel movements and gut health.",
    imagePath: "",
    imageUrl: "",
    features: ["Soluble Fiber", "Prebiotic", "Natural Regularity"]
  },
  {
    id: 34,
    name: "CranDefend UT",
    price: 18.50,
    category: "Wellness",
    shortDescription: "Concentrated cranberry for urinary tract health.",
    description: "High-potency cranberry extract with D-Mannose for targeted support of the urinary system and overall feminine hygiene.",
    imagePath: "",
    imageUrl: "",
    features: ["Cranberry Power", "D-Mannose", "UT Support"]
  },
  {
    id: 35,
    name: "ZincImmune Lozenges",
    price: 12.99,
    category: "Immune Support",
    shortDescription: "Targeted throat and immune support.",
    description: "Great-tasting lozenges that deliver ionic zinc directly to the throat area for fast-acting seasonal support.",
    imagePath: "",
    imageUrl: "",
    features: ["Ionic Zinc", "Fast Acting", "Seasonal Support"]
  },
  {
    id: 36,
    name: "MuscleMax BCAA",
    price: 36.00,
    category: "Performance",
    shortDescription: "Essential amino acids for muscle preservation.",
    description: "A 2:1:1 ratio of Leucine, Isoleucine, and Valine to prevent muscle breakdown during intense calorie deficits or heavy training.",
    imagePath: "",
    imageUrl: "",
    features: ["2:1:1 Ratio", "Anti-Catabolic", "Sugar Free"]
  },
  {
    id: 37,
    name: "LuteinPlus Vision",
    price: 29.99,
    category: "Eye Health",
    shortDescription: "Macular pigment booster for sharp vision.",
    description: "Specifically formulated to improve contrast sensitivity and protect against oxidative damage to the retina.",
    imagePath: "",
    imageUrl: "",
    features: ["Macular Health", "Contrast Support", "Antioxidant"]
  },
  {
    id: 38,
    name: "TurmeroGold Liquid",
    price: 43.00,
    category: "Joint Care",
    shortDescription: "Nano-micelle turmeric for 185x better absorption.",
    description: "The most bioavailable turmeric on the market. Targets systemic inflammation and joint discomfort with clinical precision.",
    imagePath: "",
    imageUrl: "",
    features: ["Nano-Micelle", "High Bioavailability", "Joint Relief"]
  },
  {
    id: 39,
    name: "IronStrong Spray",
    price: 17.50,
    category: "Vitality",
    shortDescription: "Oral spray iron for those who hate pills.",
    description: "A convenient spray that enters the bloodstream directly through the oral mucosa, bypassing the digestive system for fast action.",
    imagePath: "",
    imageUrl: "",
    features: ["Oral Spray", "Fast Absorption", "No Constipation"]
  },
  {
    id: 40,
    name: "GabaRest Relax",
    price: 24.50,
    category: "Wellness",
    shortDescription: "Direct inhibitory neurotransmitter support.",
    description: "GABA helps to quiet the mind and reduce over-stimulation of neurons, making it perfect for winding down after a stressful day.",
    imagePath: "",
    imageUrl: "",
    features: ["GABA Support", "Neuro-Calmer", "Pure Ingredient"]
  },
  {
    id: 41,
    name: "B-Total Complex",
    price: 26.00,
    category: "Performance",
    shortDescription: "The complete family of B-vitamins for energy.",
    description: "Full spectrum B-Complex to support energy metabolism, nervous system health, and healthy red blood cell formation.",
    imagePath: "",
    imageUrl: "",
    features: ["Full Spectrum", "Energy Release", "Stress Support"]
  },
  {
    id: 42,
    name: "CurcuminShield Pro",
    price: 47.99,
    category: "Joint Care",
    shortDescription: "Professional grade curcumin with piperine.",
    description: "Enhanced with black pepper extract to increase absorption by 2000%. Powerful naturally-derived anti-inflammatory support.",
    imagePath: "",
    imageUrl: "",
    features: ["Piperine Enhanced", "Clinically Validated", "Heart Supported"]
  },
  {
    id: 43,
    name: "ResveraYouth Vital",
    price: 52.00,
    category: "Vitality",
    shortDescription: "Longevity support with pure Trans-Resveratrol.",
    description: "Activate your longevity genes (Sirtuins) and support cellular health with our highly purified Resveratrol extract.",
    imagePath: "",
    imageUrl: "",
    features: ["Longevity Secret", "Sirtuin Activation", "Cell Health"]
  },
  {
    id: 44,
    name: "BrainSharp Ginkgo",
    price: 28.50,
    category: "Brain Health",
    shortDescription: "Enhanced cerebral circulation and alert mind.",
    description: "Using standardized Ginkgo Biloba extract to support blood flow to the brain and improve cognitive processing speed.",
    imagePath: "",
    imageUrl: "",
    features: ["Mental Alertness", "Cerebral Flow", "Ancient Wisdom"]
  },
  {
    id: 45,
    name: "EchinaceaForce Max",
    price: 21.99,
    category: "Immune Support",
    shortDescription: "Potent herbal defense for immune resilience.",
    description: "Standardized Echinacea Purperea to kickstart your immune response when you feel the first signs of under-the-weather symptoms.",
    imagePath: "",
    imageUrl: "",
    features: ["Herbal Defense", "Standardized", "Short Term Use"]
  },
  {
    id: 46,
    name: "SawPalmetto Guard",
    price: 32.50,
    category: "Vitality",
    shortDescription: "Prostate and urinary health support for men.",
    description: "Supports healthy testosterone levels and reduces night-time urgency for maturing men seeking better sleep and health.",
    imagePath: "",
    imageUrl: "",
    features: ["Prostate Health", "Men's Routine", "Better Sleep"]
  },
  {
    id: 47,
    name: "EveningPrimrose Oil",
    price: 24.00,
    category: "Beauty",
    shortDescription: "GLA-rich oil for skin health and balance.",
    description: "Supports skin barrier function and hormonal harmony for women through high concentrations of Gamma-Linolenic Acid.",
    imagePath: "",
    imageUrl: "",
    features: ["Hormonal Balance", "Skin Barrier", "Omega-6"]
  },
  {
    id: 48,
    name: "MilkThistle Detox Plus",
    price: 27.99,
    category: "Wellness",
    shortDescription: "Advanced silymarin for total liver defense.",
    description: "Highly concentrated milk thistle extract to support liver enzyme levels and protect against environmental toxins.",
    imagePath: "",
    imageUrl: "",
    features: ["80% Silymarin", "Liver Guard", "Daily Detox"]
  },
  {
    id: 49,
    name: "Prostaclear Essential",
    price: 38.00,
    category: "Vitality",
    shortDescription: "Complete prostate and bladder comfort.",
    description: "A synergistic blend of Saw Palmetto, Zinc, and Selenium for total masculine wellness and urinary comfort.",
    imagePath: "",
    imageUrl: "",
    features: ["Mineral Enhanced", "Bladder Comfort", "Male Specific"]
  },
  {
    id: 50,
    name: "ValerianaRest Sleep",
    price: 19.50,
    category: "Wellness",
    shortDescription: "The ultimate natural tranquilizer for sleep.",
    description: "Reduces sleep latency and improves deep sleep quality with high-potency Valerian root extract. Calming and natural.",
    imagePath: "",
    imageUrl: "",
    features: ["Deep Sleep", "Natural Sedative", "Wake Refreshed"]
  },
  {
    id: 51,
    name: "GlucosamineMax Plus",
    price: 33.99,
    category: "Joint Care",
    shortDescription: "Maximum tissue repair and joint lubrication.",
    description: "Targets cartilage repair and improves synovial fluid viscosity for smoother, pain-free joint movement during activity.",
    imagePath: "",
    imageUrl: "",
    features: ["Tissue Repair", "Lubrication", "High Potency"]
  },
  {
    id: 52,
    name: "VitaminA Vision Elite",
    price: 14.50,
    category: "Eye Health",
    shortDescription: "Essential Retinol for night vision support.",
    description: "Supports the cornea and allows for better adjustment to dark environments, crucial for low-light vision and health.",
    imagePath: "",
    imageUrl: "",
    features: ["Night Vision", "Cornea Support", "Immune Health"]
  },
  {
    id: 53,
    name: "PropolisImmune Spray",
    price: 21.00,
    category: "Immune Support",
    shortDescription: "Nature's strongest antimicrobial from beehives.",
    description: "Bee propolis spray provides targeted immune support for the throat and upper respiratory tract with 300+ natural compounds.",
    imagePath: "",
    imageUrl: "",
    features: ["Bee Propolis", "Bio-Flavonoids", "Natural Defense"]
  },
  {
    id: 54,
    name: "SeleniumHeart Plus",
    price: 23.50,
    category: "Heart Health",
    shortDescription: "Vital trace mineral for thyroid and heart.",
    description: "Highly absorbable Selenium (L-Selenomethionine) to protect tissues from oxidative stress and support metabolic health.",
    imagePath: "",
    imageUrl: "",
    features: ["Trace Mineral", "Thyroid Health", "Cell Protector"]
  },
  {
    id: 55,
    name: "AlphaLipoic Acid G+",
    price: 35.99,
    category: "Wellness",
    shortDescription: "The universal antioxidant for cellular energy.",
    description: "ALA works in both water and fat-soluble tissues, supporting healthy nerve function and glucose metabolism.",
    imagePath: "",
    imageUrl: "",
    features: ["Nerve Health", "Blood Sugar", "Universal Defense"]
  },
  {
    id: 56,
    name: "BromelainDigest Pro",
    price: 25.50,
    category: "Digestive Health",
    shortDescription: "Pineapple enzymes for protein breakdown.",
    description: "Highly potent Bromelain targeted at reducing systemic inflammation and improving protein digestion efficiency.",
    imagePath: "",
    imageUrl: "",
    features: ["Protein Digestion", "Anti-Inflammatory", "Natural Source"]
  },
  {
    id: 57,
    name: "ColostrumImmune Rise",
    price: 46.00,
    category: "Immune Support",
    shortDescription: "Rich in antibodies and growth factors for gut.",
    description: "Ethically sourced bovine colostrum to strengthen gut barrier integrity and provide passive immunity through IGG antibodies.",
    imagePath: "",
    imageUrl: "",
    features: ["IGG Antibodies", "Gut Barrier", "Recovery Support"]
  },
  {
    id: 58,
    name: "GlutathioneMaster Pro",
    price: 65.00,
    category: "Wellness",
    shortDescription: "The master antioxidant for total detox.",
    description: "Reduced glutathione for maximal bioavailability, crucial for liver health, skin whitening, and cellular detoxification.",
    imagePath: "",
    imageUrl: "",
    features: ["Detox Master", "Skin Health", "Cellular Shield"]
  },
  {
    id: 59,
    name: "L-Carnitine Energy",
    price: 28.99,
    category: "Performance",
    shortDescription: "Fat-to-energy transport for weight goals.",
    description: "Supports the transport of long-chain fatty acids into mitochondria to be burned as fuel, enhancing brain and metabolic energy.",
    imagePath: "",
    imageUrl: "",
    features: ["Fat Metabolism", "Brain Energy", "Heart Support"]
  },
  {
    id: 60,
    name: "SpirulinaSupra Bio",
    price: 22.00,
    category: "Supplements",
    shortDescription: "Nutrient-dense superfood for vitality.",
    description: "The highest quality organic Spirulina providing plant-based protein, chlorophyll, and essential amino acids in one tablet.",
    imagePath: "",
    imageUrl: "",
    features: ["Superfood", "Iron Rich", "Chlorophyll Power"]
  },
  {
    id: 61,
    name: "ChlorellaClean Plus",
    price: 24.50,
    category: "Vitality",
    shortDescription: "Broken cell wall chlorella for heavy metal detox.",
    description: "Highly effective at binding to environmental toxins and supporting digestive health with its unique fibrous cell wall.",
    imagePath: "",
    imageUrl: "",
    features: ["Heavy Metal Bind", "Clean Sourced", "Digestive Flow"]
  },
  {
    id: 62,
    name: "GarlicPure Heart",
    price: 19.99,
    category: "Heart Health",
    shortDescription: "Odorless aged garlic for blood pressure.",
    description: "Concentrated Allicin-rich garlic extract that supports cardiovascular health without the social cost of garlic breath.",
    imagePath: "",
    imageUrl: "",
    features: ["Odorless", "Allicin Rich", "BP Support"]
  },
  {
    id: 63,
    name: "GinkgoNeuro Guard",
    price: 27.00,
    category: "Brain Health",
    shortDescription: "Mental clarity and peripheral circulation helper.",
    description: "Enhanced formula for better micro-circulation to the extremities and cerebral cortex, promoting warmer hands and sharper minds.",
    imagePath: "",
    imageUrl: "",
    features: ["Warm Hands", "Memory Support", "Natural Herbal"]
  },
  {
    id: 64,
    name: "RhodiolaStress Fuel",
    price: 33.50,
    category: "Mental Wellness",
    shortDescription: "Endurance and stress management from the cold.",
    description: "A mountain-grown adaptogen that helps your body survive extreme physical and psychological stress without fatigue.",
    imagePath: "",
    imageUrl: "",
    features: ["Physical Stamina", "Stress Defense", "Pure Extract"]
  },
  {
    id: 65,
    name: "5-HTP Mood Master",
    price: 26.99,
    category: "Wellness",
    shortDescription: "Direct serotonin precursor for a happy outlook.",
    description: "Naturally derived from Griffonia seeds, 5-HTP supports healthy serotonin levels for improved mood and appetite control.",
    imagePath: "",
    imageUrl: "",
    features: ["Mood Support", "Appetite Control", "Better Sleep"]
  },
  {
    id: 66,
    name: "PauDarco Immune",
    price: 18.00,
    category: "Immune Support",
    shortDescription: "Traditional Amazonian bark for immune health.",
    description: "Rich in Lapachol, this traditional herbal remedy supports the body's natural resistance to environmental stressors.",
    imagePath: "",
    imageUrl: "",
    features: ["Amazonian Herb", "Natural Resistance", "Pure Bark"]
  },
  {
    id: 67,
    name: "MacaPeak Energy",
    price: 25.00,
    category: "Performance",
    shortDescription: "Andean superfood for vitality and stamina.",
    description: "Gelatinized Maca for easier digestion, providing sustained energy and supporting libido for both men and women.",
    imagePath: "",
    imageUrl: "",
    features: ["Stamina Boost", "Libido Support", "Gelatinized"]
  },
  {
    id: 68,
    name: "BilberryVision Aid",
    price: 30.00,
    category: "Eye Health",
    shortDescription: "Anthocyanin support for micro-circulation.",
    description: "Highly concentrated Bilberry extract to support the tiny blood vessels in the eyes, improving night vision and health.",
    imagePath: "",
    imageUrl: "",
    features: ["Anthocyanin Rich", "Micro-Circulation", "Retina Support"]
  },
  {
    id: 69,
    name: "CatClaw Defense Plus",
    price: 21.50,
    category: "Immune Support",
    shortDescription: "Peruvian vine for joint and immune support.",
    description: "Contains powerful alkaloids that support white blood cell function and help manage intermittent joint discomfort.",
    imagePath: "",
    imageUrl: "",
    features: ["Uncaria Tomentosa", "WBC Support", "Joint Comfort"]
  },
  {
    id: 70,
    name: "OliveLeaf Extract Pro",
    price: 23.99,
    category: "Immune Support",
    shortDescription: "Oleuropein-rich support for blood pressure.",
    description: "Powerful plant-based defense that supports cardiovascular health and a balanced immune system through natural polyphenols.",
    imagePath: "",
    imageUrl: "",
    features: ["20% Oleuropein", "BP Support", "Broad Defense"]
  },
  {
    id: 71,
    name: "BiotinGlow 10000",
    price: 16.99,
    category: "Beauty",
    shortDescription: "Ultra-strength Vitamin B7 for fast growth.",
    description: "Maximum strength Biotin for those seeking noticeable improvements in hair thickness and nail strength in minimal time.",
    imagePath: "",
    imageUrl: "",
    features: ["Hair Thickness", "Nail Strength", "Ultra Strong"]
  },
  {
    id: 72,
    name: "CordycepsStamina Pro",
    price: 45.00,
    category: "Performance",
    shortDescription: "Mushroom energy for lung and heart stamina.",
    description: "Increases ATP production and improves oxygen utilization efficiency, making it the favorite of endurance athletes.",
    imagePath: "",
    imageUrl: "",
    features: ["ATP Production", "Oxygen Flow", "Endurance Aid"]
  },
  {
    id: 73,
    name: "ReishiZen Wellness",
    price: 39.00,
    category: "Wellness",
    shortDescription: "The mushroom of immortality for longevity.",
    description: "Reduces stress through nervous system modulation and supports deep, restorative sleep and immune longevity.",
    imagePath: "",
    imageUrl: "",
    features: ["Immortal Mushroom", "Immune Balance", "Stress Calm"]
  },
  {
    id: 74,
    name: "LionMane Focus Elite",
    price: 42.50,
    category: "Brain Health",
    shortDescription: "NGF booster for neural health and focus.",
    description: "Stimulates Nerve Growth Factor (NGF) to help maintain neural connections and support cognitive clarity and memory.",
    imagePath: "",
    imageUrl: "",
    features: ["NGF Support", "Neural Health", "Real Mushroom"]
  },
  {
    id: 75,
    name: "ChagaImmune Shield",
    price: 38.00,
    category: "Immune Support",
    shortDescription: "The king of mushrooms for antioxidant power.",
    description: "Wild-harvested chaga provides massive amounts of SOD and Melanin, supporting skin and immune system resilience.",
    imagePath: "",
    imageUrl: "",
    features: ["Massive SOD", "Antioxidant King", "Wild Harvested"]
  },
  {
    id: 76,
    name: "SiberianGinseng Max",
    price: 24.99,
    category: "Vitality",
    shortDescription: "Fight physical fatigue and support focus.",
    description: "A gentle adaptogen perfect for everyday use to maintain energy balance and increase physical workload capacity.",
    imagePath: "",
    imageUrl: "",
    features: ["Work Capacity", "Gentle Vitality", "Daily Support"]
  },
  {
    id: 77,
    name: "KoreanPanax Red",
    price: 55.00,
    category: "Performance",
    shortDescription: "Traditional red ginseng for peak drive.",
    description: "Aged 6 years for maximal ginsenoside content. The gold standard for masculine vitality and mental sharp-ness.",
    imagePath: "",
    imageUrl: "",
    features: ["6-Year Aged", "Male Vitality", "Gold Standard"]
  },
  {
    id: 78,
    name: "AshwagandhaKSM-66",
    price: 29.50,
    category: "Mental Wellness",
    shortDescription: "The most clinically studied ashwagandha.",
    description: "KSM-66 provides high concentration root extract to support healthy cortisol levels and emotional resilience.",
    imagePath: "",
    imageUrl: "",
    features: ["KSM-66 Extract", "Cortisol Balance", "Emotional Strength"]
  },
  {
    id: 79,
    name: "HolyBasil Rest Balance",
    price: 22.00,
    category: "Wellness",
    shortDescription: "Tulsi extract for a peaceful body and mind.",
    description: "Traditional Ayurvedic herb that helps the body cope with spiritual and physical stressors with calm assurance.",
    imagePath: "",
    imageUrl: "",
    features: ["Ayurvedic Herb", "Tulsi Power", "Mind-Body Balance"]
  },
  {
    id: 80,
    name: "AstaxanthinCell Shield",
    price: 37.00,
    category: "Beauty",
    shortDescription: "6000x stronger than Vitamin C.",
    description: "Protects the skin from UV-induced damage and supports muscle recovery by scavenging free radicals with unmatched power.",
    imagePath: "",
    imageUrl: "",
    features: ["UV Protection", "Skin Glow", "Performance Aid"]
  },
  {
    id: 81,
    name: "L-Theanine Relax Focus",
    price: 19.99,
    category: "Brain Health",
    shortDescription: "Calm focus without the drowsiness.",
    description: "A natural amino acid that increases Alpha brain waves, perfect for meditation or intense creative work.",
    imagePath: "",
    imageUrl: "",
    features: ["Alpha Waves", "Creative Focus", "Pure Amino"]
  },
  {
    id: 82,
    name: "D-Ribose Heart Energy",
    price: 32.00,
    category: "Heart Health",
    shortDescription: "Fuel the heart's energy at the cellular level.",
    description: "The structural backbone of ATP. Crucial for heart recovery and those with high physical energy demands.",
    imagePath: "",
    imageUrl: "",
    features: ["ATP Backbone", "Heart Fuel", "Muscle Recovery"]
  },
  {
    id: 83,
    name: "L-Glutamine Gut Restore",
    price: 26.50,
    category: "Digestive Health",
    shortDescription: "Fuel for the cells lining your gut.",
    description: "Supports intestinal wall integrity and recovery after workouts. The most abundant amino acid in the human body.",
    imagePath: "",
    imageUrl: "",
    features: ["Gut Lining", "Amino Acid", "Leaky Gut Guard"]
  },
  {
    id: 84,
    name: "MelatoninQuick Dissolve",
    price: 13.99,
    category: "Wellness",
    shortDescription: "Fast-acting sleep support sublingual tab.",
    description: "Dissolves in seconds to help you catch your flight or fall asleep when your schedule is upside down.",
    imagePath: "",
    imageUrl: "",
    features: ["Sublingual", "Fast Acting", "Jet Lag Hero"]
  },
  {
    id: 85,
    name: "VitaminCHesperidin+",
    price: 24.95,
    category: "Immune Support",
    shortDescription: "Bioflavonoid-boosted immune shield.",
    description: "Adds Hesperidin for improved Vitamin C absorption and blood vessel support. Gentle and effective.",
    imagePath: "",
    imageUrl: "",
    features: ["Bioflavonoids", "Gentle C", "Daily Defense"]
  },
  {
    id: 86,
    name: "ElderberrySyrup Daily",
    price: 28.00,
    category: "Immune Support",
    shortDescription: "Delicious seasonal immune support syrup.",
    description: "Alcohol-free and kid-friendly syrup packed with Sambucus nigra goodness for the whole family.",
    imagePath: "",
    imageUrl: "",
    features: ["Alcohol Free", "Kid Friendly", "Great Taste"]
  },
  {
    id: 87,
    name: "MagnesiumCitrate Easy",
    price: 18.99,
    category: "Digestive Health",
    shortDescription: "Support digestion and muscle relaxation.",
    description: "A gentle magnesium that supports bowel regularity and helps with muscle cramps and evening tension.",
    imagePath: "",
    imageUrl: "",
    features: ["Bowel Support", "Cramp Relief", "Daily Mineral"]
  },
  {
    id: 88,
    name: "AlphaGPC Focus Fuel",
    price: 56.00,
    category: "Brain Health",
    shortDescription: "Premier choline source for brain power.",
    description: "Crosses the blood-brain barrier effectively to boost acetylcholine levels, enhancing memory and athletic power.",
    imagePath: "",
    imageUrl: "",
    features: ["Choline Source", "Memory Max", "Athletic Power"]
  },
  {
    id: 89,
    name: "PterostilbeneLongevity",
    price: 49.00,
    category: "Vitality",
    shortDescription: "Resveratrol's more stable 'cousin'.",
    description: "Better bioavailability than Resveratrol. Supports healthy aging and cognitive function through potent antioxidant action.",
    imagePath: "",
    imageUrl: "",
    features: ["High Bio-Use", "Aging Support", "Stable Shield"]
  },
  {
    id: 90,
    name: "NicotinamideRiboside+",
    price: 79.99,
    category: "Vitality",
    shortDescription: "Boost NAD+ levels for cellular repair.",
    description: "The cutting edge of longevity science. Supports mitochondrial health and energy production at the foundation of life.",
    imagePath: "",
    imageUrl: "",
    features: ["NAD+ Booster", "Cell Repair", "Youth Fuel"]
  },
  {
    id: 91,
    name: "PhosphatidylserinePS",
    price: 39.50,
    category: "Brain Health",
    shortDescription: "Cortisol management and memory support.",
    description: "Clinical support for brain cell membranes, helping reduce stress-induced cortisol and improving recall.",
    imagePath: "",
    imageUrl: "",
    features: ["Memory Recall", "Cortisol Guard", "Brain Vitality"]
  },
  {
    id: 92,
    name: "GrapeSeedElite Extract",
    price: 22.00,
    category: "Heart Health",
    shortDescription: "95% Proanthocyanidins for circulation.",
    description: "Massive antioxidant support for blood vessels and skin collagen. Keeps your heart and legs feeling light.",
    imagePath: "",
    imageUrl: "",
    features: ["High OPC", "Blood Flow", "Skin Strength"]
  },
  {
    id: 93,
    name: "PycnogenolSkin Plus",
    price: 58.00,
    category: "Beauty",
    shortDescription: "French Maritime Pine Bark for hydration.",
    description: "Premium extract to improve skin hydration and elasticity while protecting against environmental stressors and age.",
    imagePath: "",
    imageUrl: "",
    features: ["Pine Bark Extract", "Hydration Hero", "Elasticity Boost"]
  },
  {
    id: 94,
    name: "QuercetinBromelain+",
    price: 34.50,
    category: "Immune Support",
    shortDescription: "Natural seasonal histamine support.",
    description: "Helps stabilize mast cells for a balanced immune response during allergy seasons. Powerful antioxidant duo.",
    imagePath: "",
    imageUrl: "",
    features: ["Histamine Support", "Bioflavonoid", "Seasonal Relief"]
  },
  {
    id: 95,
    name: "DongQuai Female Vital",
    price: 24.00,
    category: "Wellness",
    shortDescription: "Traditional female reproductive health oil.",
    description: "The 'female ginseng' supporting blood flow and pelvic health through traditional botanical wisdom.",
    imagePath: "",
    imageUrl: "",
    features: ["Female Ginseng", "Pelvic Support", "Traditional Tea"]
  },
  {
    id: 96,
    name: "BlackCohosh Relax",
    price: 21.00,
    category: "Wellness",
    shortDescription: "Menopausal symptom relief and balance.",
    description: "Supports temperature regulation and restful sleep during the transition phases of womanhood.",
    imagePath: "",
    imageUrl: "",
    features: ["Menopause Support", "Cycle Balance", "Natural Herb"]
  },
  {
    id: 97,
    name: "SaffronMood Elite",
    price: 35.00,
    category: "Mental Wellness",
    shortDescription: "Clinically proven saffron for bright mood.",
    description: "Using the highest grade Crocus Sativus to support emotional well-being and weight management through satiety.",
    imagePath: "",
    imageUrl: "",
    features: ["Mood Brightener", "Satiety Support", "Rare Extract"]
  },
  {
    id: 98,
    name: "InositolNerve Calm",
    price: 23.50,
    category: "Wellness",
    shortDescription: "Supports cellular signaling and mood.",
    description: "A crucial component of cell membranes that helps with insulin signaling and emotional regulation.",
    imagePath: "",
    imageUrl: "",
    features: ["Cell Signaling", "PCOS Support", "Mind Calm"]
  },
  {
    id: 99,
    name: "ArgininePerformance+",
    price: 19.50,
    category: "Performance",
    shortDescription: "High-dose L-Arginine for muscle growth.",
    description: "Essential precursor to nitric oxide, improving vascular health and physical training outcomes.",
    imagePath: "",
    imageUrl: "",
    features: ["Vascular Health", "Pump Factor", "Pure Amino"]
  },
  {
    id: 100,
    name: "CitrullineMalate Max",
    price: 36.99,
    category: "Performance",
    shortDescription: "Delay fatigue and boost workout endurance.",
    description: "Helps clear metabolic waste from muscles, allowing you to train harder and longer with faster recovery.",
    imagePath: "",
    imageUrl: "",
    features: ["Endurance Boost", "Energy Sustain", "Pure Power"]
  },
  {
    id: 101,
    name: "BetaAlanine Tingle",
    price: 24.00,
    category: "Performance",
    shortDescription: "Buffers muscle acidity for extra reps.",
    description: "Increases muscle carnosine levels, giving you the ability to push through the burn during high-intensity sets.",
    imagePath: "",
    imageUrl: "",
    features: ["Carnosine Booster", "Rep Max", "Workout Power"]
  },
  {
    id: 102,
    name: "CreatineMonohydrate Pure",
    price: 29.99,
    category: "Performance",
    shortDescription: "The gold standard for muscle and brain energy.",
    description: "Pure micronized creatine monohydrate for increased strength, power, and cognitive resilience.",
    imagePath: "",
    imageUrl: "",
    features: ["Micronized", "Strength Support", "Pure Purity"]
  }
    */
];
